name: Build Android App and Release APK
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hrueger/setup-nativescript@v1.0.0
      - name: Download dependencies
        run: npm ci
      - name: Install Android SDK v28
        run: sdkmanager "tools" "platform-tools" "platforms;android-28" "build-tools;28.0.3" > /dev/null
      - name: Build apk
        run: tns build android --env.production
      - name: Archive build apk
        uses: actions/upload-artifact@v1
        with:
          name: bewegungsmelder
          path: platforms/android/app/build/outputs/apk/